### ISSUE TITLE
npm run dev命令报错

### ISSUE THREAD

**Issue by ollieSk8** [cooking-demo/simple#1]
npm run dev命令报错 直接下面的错误！

[cooking] - Loaded success: vue2
[cooking] - Loaded success: lint

[cooking] - Loading server...
[cooking] - Listening at http://localhost:8888

ERROR in ./src/app.vue
Module build failed: Error: Cannot find module 'vue-template-compiler'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/ollie/myspace/simple/node_modules/vue-loader/lib/parser.js:1:78)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/ollie/myspace/simple/node_modules/vue-loader/lib/loader.js:3:13)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
 @ ./src/index.js 7:11-27
 @ multi app
Child html-webpack-plugin for "index.html":

webpack: bundle is now VALID.

**Comment by ollieSk8** [comment]
额 解决了 是因为缺少依赖，vue-template-compiler，直接 npm i vue-template-compiler -D ,解决~

**Comment by QingWei-Li** [comment]
vue-loader 10 后就不再内置 vue-template-compiler 了，我会发个版本修复这个问题

**Comment by QingWei-Li** [comment]
原来已经发了，直接把 cooking-vue2 升级到 0.3.0 即可

**Comment by ollieSk8** [comment]
666 回复的够快

**Comment by ghostcode** [comment]
@QingWei-Li Starting in npm3 it no longer auto-install peer dependencies for you
